version: '2'
services:
  proxy:
    build:
      context: ./proxy
    ports:
    - 8000:8080
    depends_on:
    - gemstash
    environment:
      PROXY_TARGET_URL: "http://gemstash:9292"
      IPS_ACCESS_WHITELIST: 172.18.0.1
      BASIC_AUTH_TOKEN: abcd
  gemstash:
    build: .
    ports:
    - 9292:9292
    volumes:
    - ./gemstash-data:/var/lib/gemstash
    depends_on:
    - postgres
    environment:
      DB_HOST: postgres
      DB_USER: gemstash
      DB_PASSWORD: gemstash
      DB_NAME: gemstash
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_RANDOM_ROOT_PASSWORD: 1
      POSTGRES_USER: gemstash
      POSTGRES_PASSWORD: gemstash
      POSTGRES_DATABASE: gemstash
